[tool.poetry]
name = "py-mine"
version = "0.1.0"
description = "A small implementation of mine sweeper using pygame"
authors = ["Daniel Suveges <daniel.suveges@protonmail.com>"]
readme = "README.md"
packages = [{include = "py_mine"}]

[tool.poetry.dependencies]
python = "3.8.15"
pygame = "^2.1.3"
numpy = "^1.24.2"

[tool.poetry.group.dev.dependencies]
ipython = "^8.10.0"
flake8 = "^6.0.0"
black = "^23.1.0"
pytest = "^7.2.1"
pre-commit = "^3.0.4"
mypy = "^1.0.1"
flake8-docstrings = "^1.7.0"
isort = "^5.12.0"
flake8-type-checking = "^2.3.0"
flake8-annotations = "^3.0.0"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.6"
ipykernel = "^6.21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
