matrix_parameters:
  x_dim: 10
  y_dim: 15
  mine_count: 10
plot_parameters:
  unit_length: 30
  unclicked:
    base_color: gray70
    light_color: gray77
    dark_color: gray57
  flag:
    base_color: grey17
    flag_color: crimson
  clicked:
    base_color: gray78
    border_color: gray62
    number_colors:
      - cornflowerblue # 1
      - chartreuse4 # 2
      - firebrick1 # 3
      - midnightblue # 4
      - darkred # 5
      - olivedrab # 6
      - darkslategray # 7
      - coral # 8
